#!/usr/bin/env python3
"""为缺失 package_report.md 的 source package 自动生成报告。"""
import json
from pathlib import Path

BASE = Path(r"D:\MyStudySpace")
PACKAGES_DIR = BASE / "俄语资料整理试验区" / "_source_packages"

SOURCES_TO_CHECK = [
    "diag-0011", "diag-0002", "diag-0009", "diag-0010",
    "diag-0001", "diag-0029", "diag-0006", "diag-0008",
]


def generate_report(pkg_dir: Path) -> str:
    """Generate package_report.md for a source package."""
    # Load source.json
    with open(pkg_dir / "source.json", "r", encoding="utf-8") as f:
        source = json.load(f)

    source_id = source.get("source_id", "unknown")
    source_title = source.get("source_title", "unknown")
    source_path = source.get("source_path", "unknown")

    # Load pages.json
    pages = []
    pages_path = pkg_dir / "pages.json"
    if pages_path.exists():
        with open(pages_path, "r", encoding="utf-8") as f:
            pages = json.load(f)

    # Load sentence_candidates.json
    candidates = []
    candidates_path = pkg_dir / "sentence_candidates.json"
    if candidates_path.exists():
        with open(candidates_path, "r", encoding="utf-8") as f:
            candidates = json.load(f)

    # Load sentence_records.json
    records = []
    records_path = pkg_dir / "sentence_records.json"
    if records_path.exists():
        with open(records_path, "r", encoding="utf-8") as f:
            records = json.load(f)

    # Stats
    total_pages = len(pages)
    total_candidates = len(candidates)
    total_records = len(records)

    # Check record quality
    zh_empty = sum(1 for r in records if not r.get("zh", "").strip())
    has_surface_forms = sum(1 for r in records if r.get("surface_forms"))
    has_page = sum(1 for r in records if r.get("page_or_location"))

    # Build report
    report = []
    report.append(f"# Source Package Report: {source_id}\n")
    report.append(f"- **Source ID**: {source_id}")
    report.append(f"- **Title**: {source_title}")
    report.append(f"- **Source Path**: {source_path}")
    report.append(f"- **Generated**: auto-generated by generate_package_reports.py\n")
    report.append(f"## 文件清单\n")
    report.append(f"| 文件 | 状态 |")
    report.append(f"|------|------|")
    for fname in ["source.json", "pages.json", "sentence_candidates.json", "sentence_records.json", "package_report.md"]:
        fp = pkg_dir / fname
        if fp.exists():
            size = fp.stat().st_size
            report.append(f"| {fname} | ✅ {size} bytes |")
        else:
            report.append(f"| {fname} | ❌ 缺失 |")
    report.append(f"\n## 数据统计\n")
    report.append(f"| 指标 | 数值 |")
    report.append(f"|------|------|")
    report.append(f"| 页面数 | {total_pages} |")
    report.append(f"| 句子候选数 | {total_candidates} |")
    report.append(f"| 句子记录数 | {total_records} |")
    report.append(f"| zh 为空 | {zh_empty} |")
    report.append(f"| 有 surface_forms | {has_surface_forms} |")
    report.append(f"| 有 page_or_location | {has_page} |")

    return "\n".join(report)


def main():
    for src_id in SOURCES_TO_CHECK:
        pkg_dir = PACKAGES_DIR / src_id
        report_path = pkg_dir / "package_report.md"

        if report_path.exists():
            print(f"{src_id}: package_report.md already exists, skipping")
            continue

        if not pkg_dir.exists():
            print(f"{src_id}: directory missing, skipping")
            continue

        report = generate_report(pkg_dir)
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report)
        print(f"{src_id}: package_report.md generated")


if __name__ == "__main__":
    main()
